/* Generated By:JavaCC: Do not edit this line. alike_4Constants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface alike_4Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int tSEMICOLON = 8;
  /** RegularExpression Id. */
  int tCOLON = 9;
  /** RegularExpression Id. */
  int tCOMMA = 10;
  /** RegularExpression Id. */
  int tLPAREN = 11;
  /** RegularExpression Id. */
  int tRPAREN = 12;
  /** RegularExpression Id. */
  int tINT = 13;
  /** RegularExpression Id. */
  int tCHAR = 14;
  /** RegularExpression Id. */
  int tBOOL = 15;
  /** RegularExpression Id. */
  int tARRAY = 16;
  /** RegularExpression Id. */
  int tOF = 17;
  /** RegularExpression Id. */
  int tRANGE = 18;
  /** RegularExpression Id. */
  int tWHILE = 19;
  /** RegularExpression Id. */
  int tLOOP = 20;
  /** RegularExpression Id. */
  int tIF = 21;
  /** RegularExpression Id. */
  int tTHEN = 22;
  /** RegularExpression Id. */
  int tELSIF = 23;
  /** RegularExpression Id. */
  int tELSE = 24;
  /** RegularExpression Id. */
  int tPROCEDURE = 25;
  /** RegularExpression Id. */
  int tFUNCTION = 26;
  /** RegularExpression Id. */
  int tREF = 27;
  /** RegularExpression Id. */
  int tIS = 28;
  /** RegularExpression Id. */
  int tBEGIN = 29;
  /** RegularExpression Id. */
  int tEND = 30;
  /** RegularExpression Id. */
  int tRETURN = 31;
  /** RegularExpression Id. */
  int tPUT = 32;
  /** RegularExpression Id. */
  int tPUT_LINE = 33;
  /** RegularExpression Id. */
  int tGET = 34;
  /** RegularExpression Id. */
  int tSKIP_LINE = 35;
  /** RegularExpression Id. */
  int tINT2CHAR = 36;
  /** RegularExpression Id. */
  int tCHAR2INT = 37;
  /** RegularExpression Id. */
  int tEXIT = 38;
  /** RegularExpression Id. */
  int tNULL = 39;
  /** RegularExpression Id. */
  int tTRUE = 40;
  /** RegularExpression Id. */
  int tFALSE = 41;
  /** RegularExpression Id. */
  int tCONST_INT = 42;
  /** RegularExpression Id. */
  int tCONST_CHAR = 43;
  /** RegularExpression Id. */
  int tCONST_STRING = 44;
  /** RegularExpression Id. */
  int tASSIGN = 45;
  /** RegularExpression Id. */
  int tAND = 46;
  /** RegularExpression Id. */
  int tOR = 47;
  /** RegularExpression Id. */
  int tNOT = 48;
  /** RegularExpression Id. */
  int tEQ = 49;
  /** RegularExpression Id. */
  int tNEQ = 50;
  /** RegularExpression Id. */
  int tLT = 51;
  /** RegularExpression Id. */
  int tLE = 52;
  /** RegularExpression Id. */
  int tGT = 53;
  /** RegularExpression Id. */
  int tGE = 54;
  /** RegularExpression Id. */
  int tPLUS = 55;
  /** RegularExpression Id. */
  int tMINUS = 56;
  /** RegularExpression Id. */
  int tMULT = 57;
  /** RegularExpression Id. */
  int tDIV = 58;
  /** RegularExpression Id. */
  int tMOD = 59;
  /** RegularExpression Id. */
  int tID = 60;
  /** RegularExpression Id. */
  int tBASURA = 61;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"integer\"",
    "\"character\"",
    "\"boolean\"",
    "\"array\"",
    "\"of\"",
    "\"..\"",
    "\"while\"",
    "\"loop\"",
    "\"if\"",
    "\"then\"",
    "\"elsif\"",
    "\"else\"",
    "\"procedure\"",
    "\"function\"",
    "\"ref\"",
    "\"is\"",
    "\"begin\"",
    "\"end\"",
    "\"return\"",
    "\"put\"",
    "\"put_line\"",
    "\"get\"",
    "\"skip_line\"",
    "\"int2char\"",
    "\"char2int\"",
    "\"exit\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "<tCONST_INT>",
    "<tCONST_CHAR>",
    "<tCONST_STRING>",
    "\":=\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"=\"",
    "\"/=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "<tID>",
    "<tBASURA>",
  };

}
