/* Generated By:JavaCC: Do not edit this line. alikeConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface alikeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int tSEMICOLON = 3;
  /** RegularExpression Id. */
  int tCOLON = 4;
  /** RegularExpression Id. */
  int tCOMMA = 5;
  /** RegularExpression Id. */
  int tLPAREN = 6;
  /** RegularExpression Id. */
  int tRPAREN = 7;
  /** RegularExpression Id. */
  int tINT = 8;
  /** RegularExpression Id. */
  int tCHAR = 9;
  /** RegularExpression Id. */
  int tBOOL = 10;
  /** RegularExpression Id. */
  int tWHILE = 11;
  /** RegularExpression Id. */
  int tLOOP = 12;
  /** RegularExpression Id. */
  int tIF = 13;
  /** RegularExpression Id. */
  int tTHEN = 14;
  /** RegularExpression Id. */
  int tELSIF = 15;
  /** RegularExpression Id. */
  int tELSE = 16;
  /** RegularExpression Id. */
  int tPROCEDURE = 17;
  /** RegularExpression Id. */
  int tFUNCTION = 18;
  /** RegularExpression Id. */
  int tREF = 19;
  /** RegularExpression Id. */
  int tIS = 20;
  /** RegularExpression Id. */
  int tBEGIN = 21;
  /** RegularExpression Id. */
  int tEND = 22;
  /** RegularExpression Id. */
  int tRETURN = 23;
  /** RegularExpression Id. */
  int tARRAY = 24;
  /** RegularExpression Id. */
  int tOF = 25;
  /** RegularExpression Id. */
  int tRANGE = 26;
  /** RegularExpression Id. */
  int tPUT = 27;
  /** RegularExpression Id. */
  int tPUT_LINE = 28;
  /** RegularExpression Id. */
  int tGET = 29;
  /** RegularExpression Id. */
  int tSKIP_LINE = 30;
  /** RegularExpression Id. */
  int tINT2CHAR = 31;
  /** RegularExpression Id. */
  int tCHAR2INT = 32;
  /** RegularExpression Id. */
  int tEXIT = 33;
  /** RegularExpression Id. */
  int tNULL = 34;
  /** RegularExpression Id. */
  int tTRUE = 35;
  /** RegularExpression Id. */
  int tFALSE = 36;
  /** RegularExpression Id. */
  int tCONST_INT = 37;
  /** RegularExpression Id. */
  int tCONST_CHAR = 38;
  /** RegularExpression Id. */
  int tCONST_STRING = 39;
  /** RegularExpression Id. */
  int tASSIGN = 40;
  /** RegularExpression Id. */
  int tAND = 41;
  /** RegularExpression Id. */
  int tOR = 42;
  /** RegularExpression Id. */
  int tNOT = 43;
  /** RegularExpression Id. */
  int tEQ = 44;
  /** RegularExpression Id. */
  int tNEQ = 45;
  /** RegularExpression Id. */
  int tLT = 46;
  /** RegularExpression Id. */
  int tLE = 47;
  /** RegularExpression Id. */
  int tGT = 48;
  /** RegularExpression Id. */
  int tGE = 49;
  /** RegularExpression Id. */
  int tPLUS = 50;
  /** RegularExpression Id. */
  int tMINUS = 51;
  /** RegularExpression Id. */
  int tMULT = 52;
  /** RegularExpression Id. */
  int tDIV = 53;
  /** RegularExpression Id. */
  int tMOD = 54;
  /** RegularExpression Id. */
  int tID = 55;
  /** RegularExpression Id. */
  int COMMENT = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"integer\"",
    "\"character\"",
    "\"boolean\"",
    "\"while\"",
    "\"loop\"",
    "\"if\"",
    "\"then\"",
    "\"elsif\"",
    "\"else\"",
    "\"procedure\"",
    "\"function\"",
    "\"ref\"",
    "\"is\"",
    "\"begin\"",
    "\"end\"",
    "\"return\"",
    "\"array\"",
    "\"of\"",
    "\"..\"",
    "\"put\"",
    "\"put_line\"",
    "\"get\"",
    "\"skip_line\"",
    "\"int2char\"",
    "\"char2int\"",
    "\"exit\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "<tCONST_INT>",
    "<tCONST_CHAR>",
    "<tCONST_STRING>",
    "\":=\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"=\"",
    "\"/=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "<tID>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
  };

}
